; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30148.0 

include listing.inc

INCLUDELIB OLDNAMES

EXTRN	__imp_sinf:PROC
EXTRN	__imp_cosf:PROC
_cmtorad DD	03c8efa39r			; 0.0174533
PUBLIC	CMatrixSet
PUBLIC	CMatrixApply
PUBLIC	CMatrixMultiply
PUBLIC	CMatrixTransform
PUBLIC	CMatrixRotate
PUBLIC	CMatrixScale
PUBLIC	CMatrixTranslate
PUBLIC	CMatrixIdentity
PUBLIC	CVect3FCross
PUBLIC	CVect3FDot
PUBLIC	CMakeVect4F
PUBLIC	CMakeVect2F
PUBLIC	CMakeVect3F
;	COMDAT pdata
pdata	SEGMENT
$pdata$CMatrixApply DD imagerel $LN33@CMatrixApp
	DD	imagerel $LN33@CMatrixApp+147
	DD	imagerel $unwind$CMatrixApply
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$CMatrixMultiply DD imagerel $LN28@CMatrixMul
	DD	imagerel $LN28@CMatrixMul+178
	DD	imagerel $unwind$CMatrixMultiply
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$CMatrixTransform DD imagerel $LN4@CMatrixTra
	DD	imagerel $LN4@CMatrixTra+249
	DD	imagerel $unwind$CMatrixTransform
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$CMatrixRotate DD imagerel $LN81@CMatrixRot
	DD	imagerel $LN81@CMatrixRot+720
	DD	imagerel $unwind$CMatrixRotate
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$CMatrixScale DD imagerel $LN38@CMatrixSca
	DD	imagerel $LN38@CMatrixSca+374
	DD	imagerel $unwind$CMatrixScale
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$CMatrixTranslate DD imagerel $LN57@CMatrixTra
	DD	imagerel $LN57@CMatrixTra+379
	DD	imagerel $unwind$CMatrixTranslate
;	COMDAT xdata
xdata	SEGMENT
$unwind$CMatrixTranslate DQ 0000d681700052519r	; 1.86442e-308
	DQ	000005002001c010er		; 4.34627e-310
	DD	imagerel __GSHandlerCheck
	DD	0c0H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$CMatrixScale DQ 0000d681000042219r	; 1.8644e-308
	DD	01d010aH
	DD	imagerel __GSHandlerCheck
	DD	0c0H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$CMatrixRotate DQ 0000fa83400134219r	; 2.17738e-308
	DQ	00011882a0010982fr		; 2.43811e-308
	DQ	00013682000127825r		; 2.69884e-308
	DQ	0002b641b002d741br		; 7.61839e-308
	DQ	00028011b002a341br		; 6.67642e-308
	DD	05010H
	DD	imagerel __GSHandlerCheck
	DD	0e0H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$CMatrixTransform DQ 0002a010900030901r	; 7.23261e-308
	DD	03002H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$CMatrixMultiply DQ 00000681600031601r	; 5.65427e-310
	DD	02204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$CMatrixApply DQ 00000220400010401r	; 1.84783e-310
END
