; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30148.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_C@_0O@CIBCPLNG@CMakeMaterial@		; `string'
PUBLIC	??_C@_0CL@OFJHADBO@CMakeMaterial?5failed?5because?5na@ ; `string'
PUBLIC	??_C@_0DE@LFOBEEIG@CDestroyMaterial?5failed?5because@ ; `string'
PUBLIC	??_C@_0DH@FEKAHMEG@CDestroyMaterial?5failed?5because@ ; `string'
PUBLIC	??_C@_0BB@OMKLDMJI@CMakeRenderClass@		; `string'
PUBLIC	??_C@_0CP@LFFFKBOL@CMakerRenderClass?5failed?5becaus@ ; `string'
PUBLIC	??_C@_0CP@CHDAJNED@CMakerRenderClass?5failed?5becaus@ ; `string'
PUBLIC	??_C@_0BE@GAAOHGLP@CDestroyRenderClass@		; `string'
PUBLIC	??_C@_0DD@IOLBLGBA@CDestroyRenderClass?5failed?5beca@ ; `string'
PUBLIC	??_C@_0DG@OANPGKPE@CDestroyRenderClass?5failed?5beca@ ; `string'
PUBLIC	??_C@_0BE@NIBBBBPD@CRenderClassGetName@		; `string'
PUBLIC	??_C@_0DG@JAAINOED@CRenderClassGetName?5failed?5beca@ ; `string'
PUBLIC	??_C@_0BE@LDMFAMED@CRenderClassGetMesh@		; `string'
PUBLIC	??_C@_0DG@MPPLINNM@CRenderClassGetMesh?5failed?5beca@ ; `string'
PUBLIC	??_C@_0BI@NDFCLEDJ@CRenderClassSetMaterial@	; `string'
PUBLIC	??_C@_0DK@GDCJECCE@CRenderClassSetMaterial?5failed?5@ ; `string'
PUBLIC	??_C@_0DG@BKOJNOIH@CRenderClassSetMaterial?5failed?5@ ; `string'
PUBLIC	??_C@_0BI@NMEMGCLK@CRenderClassGetMaterial@	; `string'
PUBLIC	??_C@_0DK@NGCDIKBN@CRenderClassGetMaterial?5failed?5@ ; `string'
PUBLIC	??_C@_0DG@OAKKKOJC@CRenderClassGetMaterial?5failed?5@ ; `string'
PUBLIC	??_C@_0BK@FGMIKGEE@CRenderClassGetMaterialID@	; `string'
PUBLIC	??_C@_0DM@GBOGKMPH@CRenderClassGetMaterialID?5faile@ ; `string'
PUBLIC	??_C@_0DH@MCAOPKCI@CRenderClassGetMaterialID?5faile@ ; `string'
PUBLIC	??_C@_0EB@BPMNEBMB@CRenderClassGetMaterialID?5faile@ ; `string'
PUBLIC	??_C@_0CB@NJCGDCJJ@CRenderClassSetTriMaterialSingl@ ; `string'
PUBLIC	??_C@_0ED@FJLCFPFL@CRenderClassSetTriMaterialSingl@ ; `string'
PUBLIC	??_C@_0CB@IADLCEMO@CRenderClassGetTriMaterialSingl@ ; `string'
PUBLIC	??_C@_0ED@JMBEKINI@CRenderClassGetTriMaterialSingl@ ; `string'
PUBLIC	??_C@_0BM@EENIIEBE@CRenderClassSetTriMaterials@	; `string'
PUBLIC	??_C@_0DO@DJGCMBEA@CRenderClassSetTriMaterials?5fai@ ; `string'
PUBLIC	??_C@_0EH@PKBGPGHF@CRenderClassSetTriMaterials?5fai@ ; `string'
PUBLIC	??_C@_0BL@NLLLLNMG@CRenderClassGetTriMaterial@	; `string'
PUBLIC	??_C@_0DN@PHPMIKAF@CRenderClassGetTriMaterial?5fail@ ; `string'
PUBLIC	??_C@_0EH@MGLNFGP@CRenderClassGetTriMaterial?5fail@ ; `string'
PUBLIC	??_C@_0EL@BOICEKHA@CRenderClassGetTriMaterial?5fail@ ; `string'
PUBLIC	??_C@_0BN@MDCOFIAM@CRenderClassGetTriMaterialID@ ; `string'
PUBLIC	??_C@_0CA@FAKFBMPP@CRenderClassSetVertexDataBuffer@ ; `string'
PUBLIC	??_C@_0EC@KJBKKONJ@CRenderClassSetVertexDataBuffer@ ; `string'
PUBLIC	??_C@_0DO@JMHNBPGA@CRenderClassSetVertexDataBuffer@ ; `string'
PUBLIC	??_C@_0CA@POIOFMID@CRenderClassGetVertexDataBuffer@ ; `string'
PUBLIC	??_C@_0EC@LFNGJDGB@CRenderClassGetVertexDataBuffer@ ; `string'
PUBLIC	??_C@_0DO@MPAGMADK@CRenderClassGetVertexDataBuffer@ ; `string'
PUBLIC	??_C@_0CC@JJCNBEJH@CRenderClassGetVertexDataBuffer@ ; `string'
PUBLIC	??_C@_0EE@IGAHFBDI@CRenderClassGetVertexDataBuffer@ ; `string'
PUBLIC	??_C@_0DP@BKCMHNJM@CRenderClassGetVertexDataBuffer@ ; `string'
PUBLIC	??_C@_0EJ@LJJLCPAN@CRenderClassGetVertexDataBuffer@ ; `string'
PUBLIC	??_C@_0CA@FOGLFKED@CRenderClassSetStaticDataBuffer@ ; `string'
PUBLIC	??_C@_0EC@FPBADPMF@CRenderClassSetStaticDataBuffer@ ; `string'
PUBLIC	??_C@_0DO@NDKGGPLA@CRenderClassSetStaticDataBuffer@ ; `string'
PUBLIC	??_C@_0CA@PAEABKDP@CRenderClassGetStaticDataBuffer@ ; `string'
PUBLIC	??_C@_0EC@EDNMACHN@CRenderClassGetStaticDataBuffer@ ; `string'
PUBLIC	??_C@_0DO@IANNLAOK@CRenderClassGetStaticDataBuffer@ ; `string'
PUBLIC	??_C@_0CC@EOOCBPEI@CRenderClassGetStaticDataBuffer@ ; `string'
PUBLIC	??_C@_0EE@OHHIFJLN@CRenderClassGetStaticDataBuffer@ ; `string'
PUBLIC	??_C@_0DP@JMLAHEDI@CRenderClassGetStaticDataBuffer@ ; `string'
PUBLIC	??_C@_0EJ@CGGCENIL@CRenderClassGetStaticDataBuffer@ ; `string'
;	COMDAT ??_C@_0EJ@CGGCENIL@CRenderClassGetStaticDataBuffer@
CONST	SEGMENT
??_C@_0EJ@CGGCENIL@CRenderClassGetStaticDataBuffer@ DB 'CRenderClassGetSt'
	DB	'aticDataBufferID failed because name could not be found', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0DP@JMLAHEDI@CRenderClassGetStaticDataBuffer@
CONST	SEGMENT
??_C@_0DP@JMLAHEDI@CRenderClassGetStaticDataBuffer@ DB 'CRenderClassGetSt'
	DB	'aticDataBufferID failed because name was NULL', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0EE@OHHIFJLN@CRenderClassGetStaticDataBuffer@
CONST	SEGMENT
??_C@_0EE@OHHIFJLN@CRenderClassGetStaticDataBuffer@ DB 'CRenderClassGetSt'
	DB	'aticDataBufferID failed because rClass was invalid', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0CC@EOOCBPEI@CRenderClassGetStaticDataBuffer@
CONST	SEGMENT
??_C@_0CC@EOOCBPEI@CRenderClassGetStaticDataBuffer@ DB 'CRenderClassGetSt'
	DB	'aticDataBufferID', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0DO@IANNLAOK@CRenderClassGetStaticDataBuffer@
CONST	SEGMENT
??_C@_0DO@IANNLAOK@CRenderClassGetStaticDataBuffer@ DB 'CRenderClassGetSt'
	DB	'aticDataBuffer failed because ID was invalid', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0EC@EDNMACHN@CRenderClassGetStaticDataBuffer@
CONST	SEGMENT
??_C@_0EC@EDNMACHN@CRenderClassGetStaticDataBuffer@ DB 'CRenderClassGetSt'
	DB	'aticDataBuffer failed because rClass was invalid', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0CA@PAEABKDP@CRenderClassGetStaticDataBuffer@
CONST	SEGMENT
??_C@_0CA@PAEABKDP@CRenderClassGetStaticDataBuffer@ DB 'CRenderClassGetSt'
	DB	'aticDataBuffer', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0DO@NDKGGPLA@CRenderClassSetStaticDataBuffer@
CONST	SEGMENT
??_C@_0DO@NDKGGPLA@CRenderClassSetStaticDataBuffer@ DB 'CRenderClassSetSt'
	DB	'aticDataBuffer failed because ID was invalid', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0EC@FPBADPMF@CRenderClassSetStaticDataBuffer@
CONST	SEGMENT
??_C@_0EC@FPBADPMF@CRenderClassSetStaticDataBuffer@ DB 'CRenderClassSetSt'
	DB	'aticDataBuffer failed because rClass was invalid', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0CA@FOGLFKED@CRenderClassSetStaticDataBuffer@
CONST	SEGMENT
??_C@_0CA@FOGLFKED@CRenderClassSetStaticDataBuffer@ DB 'CRenderClassSetSt'
	DB	'aticDataBuffer', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0EJ@LJJLCPAN@CRenderClassGetVertexDataBuffer@
CONST	SEGMENT
??_C@_0EJ@LJJLCPAN@CRenderClassGetVertexDataBuffer@ DB 'CRenderClassGetVe'
	DB	'rtexDataBufferID failed because name could not be found', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0DP@BKCMHNJM@CRenderClassGetVertexDataBuffer@
CONST	SEGMENT
??_C@_0DP@BKCMHNJM@CRenderClassGetVertexDataBuffer@ DB 'CRenderClassGetVe'
	DB	'rtexDataBufferID failed because name was NULL', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0EE@IGAHFBDI@CRenderClassGetVertexDataBuffer@
CONST	SEGMENT
??_C@_0EE@IGAHFBDI@CRenderClassGetVertexDataBuffer@ DB 'CRenderClassGetVe'
	DB	'rtexDataBufferID failed because rClass was invalid', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0CC@JJCNBEJH@CRenderClassGetVertexDataBuffer@
CONST	SEGMENT
??_C@_0CC@JJCNBEJH@CRenderClassGetVertexDataBuffer@ DB 'CRenderClassGetVe'
	DB	'rtexDataBufferID', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0DO@MPAGMADK@CRenderClassGetVertexDataBuffer@
CONST	SEGMENT
??_C@_0DO@MPAGMADK@CRenderClassGetVertexDataBuffer@ DB 'CRenderClassGetVe'
	DB	'rtexDataBuffer failed because ID was invalid', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0EC@LFNGJDGB@CRenderClassGetVertexDataBuffer@
CONST	SEGMENT
??_C@_0EC@LFNGJDGB@CRenderClassGetVertexDataBuffer@ DB 'CRenderClassGetVe'
	DB	'rtexDataBuffer failed because rClass was invalid', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0CA@POIOFMID@CRenderClassGetVertexDataBuffer@
CONST	SEGMENT
??_C@_0CA@POIOFMID@CRenderClassGetVertexDataBuffer@ DB 'CRenderClassGetVe'
	DB	'rtexDataBuffer', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0DO@JMHNBPGA@CRenderClassSetVertexDataBuffer@
CONST	SEGMENT
??_C@_0DO@JMHNBPGA@CRenderClassSetVertexDataBuffer@ DB 'CRenderClassSetVe'
	DB	'rtexDataBuffer failed because ID was invalid', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0EC@KJBKKONJ@CRenderClassSetVertexDataBuffer@
CONST	SEGMENT
??_C@_0EC@KJBKKONJ@CRenderClassSetVertexDataBuffer@ DB 'CRenderClassSetVe'
	DB	'rtexDataBuffer failed because rClass was invalid', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0CA@FAKFBMPP@CRenderClassSetVertexDataBuffer@
CONST	SEGMENT
??_C@_0CA@FAKFBMPP@CRenderClassSetVertexDataBuffer@ DB 'CRenderClassSetVe'
	DB	'rtexDataBuffer', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0BN@MDCOFIAM@CRenderClassGetTriMaterialID@
CONST	SEGMENT
??_C@_0BN@MDCOFIAM@CRenderClassGetTriMaterialID@ DB 'CRenderClassGetTriMa'
	DB	'terialID', 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_0EL@BOICEKHA@CRenderClassGetTriMaterial?5fail@
CONST	SEGMENT
??_C@_0EL@BOICEKHA@CRenderClassGetTriMaterial?5fail@ DB 'CRenderClassGetT'
	DB	'riMaterial failed because class triMaterials had bad value', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0EH@MGLNFGP@CRenderClassGetTriMaterial?5fail@
CONST	SEGMENT
??_C@_0EH@MGLNFGP@CRenderClassGetTriMaterial?5fail@ DB 'CRenderClassGetTr'
	DB	'iMaterial failed because triMaterialIndex was invalid', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0DN@PHPMIKAF@CRenderClassGetTriMaterial?5fail@
CONST	SEGMENT
??_C@_0DN@PHPMIKAF@CRenderClassGetTriMaterial?5fail@ DB 'CRenderClassGetT'
	DB	'riMaterial failed because rClass was invalid', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BL@NLLLLNMG@CRenderClassGetTriMaterial@
CONST	SEGMENT
??_C@_0BL@NLLLLNMG@CRenderClassGetTriMaterial@ DB 'CRenderClassGetTriMate'
	DB	'rial', 00H					; `string'
CONST	ENDS
;	COMDAT ??_C@_0EH@PKBGPGHF@CRenderClassSetTriMaterials?5fai@
CONST	SEGMENT
??_C@_0EH@PKBGPGHF@CRenderClassSetTriMaterials?5fai@ DB 'CRenderClassSetT'
	DB	'riMaterials failed because triMaterialIndexes was NULL', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0DO@DJGCMBEA@CRenderClassSetTriMaterials?5fai@
CONST	SEGMENT
??_C@_0DO@DJGCMBEA@CRenderClassSetTriMaterials?5fai@ DB 'CRenderClassSetT'
	DB	'riMaterials failed because rClass was invalid', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BM@EENIIEBE@CRenderClassSetTriMaterials@
CONST	SEGMENT
??_C@_0BM@EENIIEBE@CRenderClassSetTriMaterials@ DB 'CRenderClassSetTriMat'
	DB	'erials', 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_0ED@JMBEKINI@CRenderClassGetTriMaterialSingl@
CONST	SEGMENT
??_C@_0ED@JMBEKINI@CRenderClassGetTriMaterialSingl@ DB 'CRenderClassGetTr'
	DB	'iMaterialSingle failed because rClass was invalid', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0CB@IADLCEMO@CRenderClassGetTriMaterialSingl@
CONST	SEGMENT
??_C@_0CB@IADLCEMO@CRenderClassGetTriMaterialSingl@ DB 'CRenderClassGetTr'
	DB	'iMaterialSingle', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0ED@FJLCFPFL@CRenderClassSetTriMaterialSingl@
CONST	SEGMENT
??_C@_0ED@FJLCFPFL@CRenderClassSetTriMaterialSingl@ DB 'CRenderClassSetTr'
	DB	'iMaterialSingle failed because rClass was invalid', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0CB@NJCGDCJJ@CRenderClassSetTriMaterialSingl@
CONST	SEGMENT
??_C@_0CB@NJCGDCJJ@CRenderClassSetTriMaterialSingl@ DB 'CRenderClassSetTr'
	DB	'iMaterialSingle', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0EB@BPMNEBMB@CRenderClassGetMaterialID?5faile@
CONST	SEGMENT
??_C@_0EB@BPMNEBMB@CRenderClassGetMaterialID?5faile@ DB 'CRenderClassGetM'
	DB	'aterialID failed because name could not be found', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0DH@MCAOPKCI@CRenderClassGetMaterialID?5faile@
CONST	SEGMENT
??_C@_0DH@MCAOPKCI@CRenderClassGetMaterialID?5faile@ DB 'CRenderClassGetM'
	DB	'aterialID failed because name was NULL', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0DM@GBOGKMPH@CRenderClassGetMaterialID?5faile@
CONST	SEGMENT
??_C@_0DM@GBOGKMPH@CRenderClassGetMaterialID?5faile@ DB 'CRenderClassGetM'
	DB	'aterialID failed because rClass was invalid', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BK@FGMIKGEE@CRenderClassGetMaterialID@
CONST	SEGMENT
??_C@_0BK@FGMIKGEE@CRenderClassGetMaterialID@ DB 'CRenderClassGetMaterial'
	DB	'ID', 00H					; `string'
CONST	ENDS
;	COMDAT ??_C@_0DG@OAKKKOJC@CRenderClassGetMaterial?5failed?5@
CONST	SEGMENT
??_C@_0DG@OAKKKOJC@CRenderClassGetMaterial?5failed?5@ DB 'CRenderClassGet'
	DB	'Material failed because ID was invalid', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0DK@NGCDIKBN@CRenderClassGetMaterial?5failed?5@
CONST	SEGMENT
??_C@_0DK@NGCDIKBN@CRenderClassGetMaterial?5failed?5@ DB 'CRenderClassGet'
	DB	'Material failed because rClass was invalid', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BI@NMEMGCLK@CRenderClassGetMaterial@
CONST	SEGMENT
??_C@_0BI@NMEMGCLK@CRenderClassGetMaterial@ DB 'CRenderClassGetMaterial', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0DG@BKOJNOIH@CRenderClassSetMaterial?5failed?5@
CONST	SEGMENT
??_C@_0DG@BKOJNOIH@CRenderClassSetMaterial?5failed?5@ DB 'CRenderClassSet'
	DB	'Material failed because ID was invalid', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0DK@GDCJECCE@CRenderClassSetMaterial?5failed?5@
CONST	SEGMENT
??_C@_0DK@GDCJECCE@CRenderClassSetMaterial?5failed?5@ DB 'CRenderClassSet'
	DB	'Material failed because rClass was invalid', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BI@NDFCLEDJ@CRenderClassSetMaterial@
CONST	SEGMENT
??_C@_0BI@NDFCLEDJ@CRenderClassSetMaterial@ DB 'CRenderClassSetMaterial', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0DG@MPPLINNM@CRenderClassGetMesh?5failed?5beca@
CONST	SEGMENT
??_C@_0DG@MPPLINNM@CRenderClassGetMesh?5failed?5beca@ DB 'CRenderClassGet'
	DB	'Mesh failed because rClass was invalid', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BE@LDMFAMED@CRenderClassGetMesh@
CONST	SEGMENT
??_C@_0BE@LDMFAMED@CRenderClassGetMesh@ DB 'CRenderClassGetMesh', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0DG@JAAINOED@CRenderClassGetName?5failed?5beca@
CONST	SEGMENT
??_C@_0DG@JAAINOED@CRenderClassGetName?5failed?5beca@ DB 'CRenderClassGet'
	DB	'Name failed because rClass was invalid', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BE@NIBBBBPD@CRenderClassGetName@
CONST	SEGMENT
??_C@_0BE@NIBBBBPD@CRenderClassGetName@ DB 'CRenderClassGetName', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0DG@OANPGKPE@CDestroyRenderClass?5failed?5beca@
CONST	SEGMENT
??_C@_0DG@OANPGKPE@CDestroyRenderClass?5failed?5beca@ DB 'CDestroyRenderC'
	DB	'lass failed because pClass was invalid', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0DD@IOLBLGBA@CDestroyRenderClass?5failed?5beca@
CONST	SEGMENT
??_C@_0DD@IOLBLGBA@CDestroyRenderClass?5failed?5beca@ DB 'CDestroyRenderC'
	DB	'lass failed because pClass was NULL', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0BE@GAAOHGLP@CDestroyRenderClass@
CONST	SEGMENT
??_C@_0BE@GAAOHGLP@CDestroyRenderClass@ DB 'CDestroyRenderClass', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0CP@CHDAJNED@CMakerRenderClass?5failed?5becaus@
CONST	SEGMENT
??_C@_0CP@CHDAJNED@CMakerRenderClass?5failed?5becaus@ DB 'CMakerRenderCla'
	DB	'ss failed because mesh was NULL', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0CP@LFFFKBOL@CMakerRenderClass?5failed?5becaus@
CONST	SEGMENT
??_C@_0CP@LFFFKBOL@CMakerRenderClass?5failed?5becaus@ DB 'CMakerRenderCla'
	DB	'ss failed because name was NULL', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0BB@OMKLDMJI@CMakeRenderClass@
CONST	SEGMENT
??_C@_0BB@OMKLDMJI@CMakeRenderClass@ DB 'CMakeRenderClass', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0DH@FEKAHMEG@CDestroyMaterial?5failed?5because@
CONST	SEGMENT
??_C@_0DH@FEKAHMEG@CDestroyMaterial?5failed?5because@ DB 'CDestroyMateria'
	DB	'l failed because pMatHandle was invalid', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0DE@LFOBEEIG@CDestroyMaterial?5failed?5because@
CONST	SEGMENT
??_C@_0DE@LFOBEEIG@CDestroyMaterial?5failed?5because@ DB 'CDestroyMateria'
	DB	'l failed because pMatHandle was NULL', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0CL@OFJHADBO@CMakeMaterial?5failed?5because?5na@
CONST	SEGMENT
??_C@_0CL@OFJHADBO@CMakeMaterial?5failed?5because?5na@ DB 'CMakeMaterial '
	DB	'failed because name was NULL', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_0O@CIBCPLNG@CMakeMaterial@
CONST	SEGMENT
??_C@_0O@CIBCPLNG@CMakeMaterial@ DB 'CMakeMaterial', 00H ; `string'
PUBLIC	CRenderClassGetStaticDataBufferID
PUBLIC	CRenderClassSetStaticDataBuffer
PUBLIC	CRenderClassGetVertexDataBufferID
PUBLIC	CRenderClassGetVertexDataBuffer
PUBLIC	CRenderClassSetVertexDataBuffer
PUBLIC	CRenderClassGetTriMaterialID
PUBLIC	CRenderClassGetTriMaterial
PUBLIC	CRenderClassSetTriMaterials
PUBLIC	CRenderClassGetTriMaterialSingle
PUBLIC	CRenderClassSetTriMaterialSingle
PUBLIC	CRenderClassGetMaterialID
PUBLIC	CRenderClassGetMaterial
PUBLIC	CRenderClassSetMaterial
PUBLIC	CRenderClassGetName
PUBLIC	CDestroyRenderClass
PUBLIC	CMakeRenderClass
PUBLIC	CDestroyMaterial
PUBLIC	CMakeMaterial
PUBLIC	CRenderClassGetMesh
PUBLIC	CRenderClassGetStaticDataBuffer
;	COMDAT pdata
pdata	SEGMENT
$pdata$CRenderClassGetStaticDataBufferID DD imagerel $LN45@CRenderCla
	DD	imagerel $LN45@CRenderCla+329
	DD	imagerel $unwind$CRenderClassGetStaticDataBufferID
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$0$CRenderClassGetStaticDataBufferID DD imagerel $LN45@CRenderCla+329
	DD	imagerel $LN45@CRenderCla+513
	DD	imagerel $chain$0$CRenderClassGetStaticDataBufferID
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$2$CRenderClassGetStaticDataBufferID DD imagerel $LN45@CRenderCla+513
	DD	imagerel $LN45@CRenderCla+594
	DD	imagerel $chain$2$CRenderClassGetStaticDataBufferID
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$CRenderClassSetStaticDataBuffer DD imagerel $LN26@CRenderCla
	DD	imagerel $LN26@CRenderCla+418
	DD	imagerel $unwind$CRenderClassSetStaticDataBuffer
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$CRenderClassGetVertexDataBufferID DD imagerel $LN45@CRenderCla
	DD	imagerel $LN45@CRenderCla+329
	DD	imagerel $unwind$CRenderClassGetVertexDataBufferID
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$0$CRenderClassGetVertexDataBufferID DD imagerel $LN45@CRenderCla+329
	DD	imagerel $LN45@CRenderCla+513
	DD	imagerel $chain$0$CRenderClassGetVertexDataBufferID
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$2$CRenderClassGetVertexDataBufferID DD imagerel $LN45@CRenderCla+513
	DD	imagerel $LN45@CRenderCla+594
	DD	imagerel $chain$2$CRenderClassGetVertexDataBufferID
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$CRenderClassGetVertexDataBuffer DD imagerel $LN26@CRenderCla
	DD	imagerel $LN26@CRenderCla+421
	DD	imagerel $unwind$CRenderClassGetVertexDataBuffer
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$CRenderClassSetVertexDataBuffer DD imagerel $LN26@CRenderCla
	DD	imagerel $LN26@CRenderCla+415
	DD	imagerel $unwind$CRenderClassSetVertexDataBuffer
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$CRenderClassGetTriMaterialID DD imagerel $LN26@CRenderCla
	DD	imagerel $LN26@CRenderCla+434
	DD	imagerel $unwind$CRenderClassGetTriMaterialID
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$CRenderClassGetTriMaterial DD imagerel $LN32@CRenderCla
	DD	imagerel $LN32@CRenderCla+548
	DD	imagerel $unwind$CRenderClassGetTriMaterial
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$CRenderClassSetTriMaterials DD imagerel $LN26@CRenderCla
	DD	imagerel $LN26@CRenderCla+442
	DD	imagerel $unwind$CRenderClassSetTriMaterials
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$CRenderClassGetTriMaterialSingle DD imagerel $LN20@CRenderCla
	DD	imagerel $LN20@CRenderCla+320
	DD	imagerel $unwind$CRenderClassGetTriMaterialSingle
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$CRenderClassSetTriMaterialSingle DD imagerel $LN20@CRenderCla
	DD	imagerel $LN20@CRenderCla+317
	DD	imagerel $unwind$CRenderClassSetTriMaterialSingle
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$CRenderClassGetMaterialID DD imagerel $LN45@CRenderCla
	DD	imagerel $LN45@CRenderCla+335
	DD	imagerel $unwind$CRenderClassGetMaterialID
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$0$CRenderClassGetMaterialID DD imagerel $LN45@CRenderCla+335
	DD	imagerel $LN45@CRenderCla+517
	DD	imagerel $chain$0$CRenderClassGetMaterialID
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$2$CRenderClassGetMaterialID DD imagerel $LN45@CRenderCla+517
	DD	imagerel $LN45@CRenderCla+598
	DD	imagerel $chain$2$CRenderClassGetMaterialID
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$CRenderClassGetMaterial DD imagerel $LN26@CRenderCla
	DD	imagerel $LN26@CRenderCla+424
	DD	imagerel $unwind$CRenderClassGetMaterial
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$CRenderClassSetMaterial DD imagerel $LN26@CRenderCla
	DD	imagerel $LN26@CRenderCla+418
	DD	imagerel $unwind$CRenderClassSetMaterial
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$CRenderClassGetName DD imagerel $LN24@CRenderCla
	DD	imagerel $LN24@CRenderCla+360
	DD	imagerel $unwind$CRenderClassGetName
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$CDestroyRenderClass DD imagerel $LN26@CDestroyRe
	DD	imagerel $LN26@CDestroyRe+447
	DD	imagerel $unwind$CDestroyRenderClass
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$CMakeRenderClass DD imagerel $LN29@CMakeRende
	DD	imagerel $LN29@CMakeRende+326
	DD	imagerel $unwind$CMakeRenderClass
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$2$CMakeRenderClass DD imagerel $LN29@CMakeRende+326
	DD	imagerel $LN29@CMakeRende+461
	DD	imagerel $chain$2$CMakeRenderClass
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$3$CMakeRenderClass DD imagerel $LN29@CMakeRende+461
	DD	imagerel $LN29@CMakeRende+546
	DD	imagerel $chain$3$CMakeRenderClass
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$CDestroyMaterial DD imagerel $LN21@CDestroyMa
	DD	imagerel $LN21@CDestroyMa+351
	DD	imagerel $unwind$CDestroyMaterial
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$CMakeMaterial DD imagerel $LN23@CMakeMater
	DD	imagerel $LN23@CMakeMater+217
	DD	imagerel $unwind$CMakeMaterial
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$2$CMakeMaterial DD imagerel $LN23@CMakeMater+217
	DD	imagerel $LN23@CMakeMater+316
	DD	imagerel $chain$2$CMakeMaterial
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$3$CMakeMaterial DD imagerel $LN23@CMakeMater+316
	DD	imagerel $LN23@CMakeMater+401
	DD	imagerel $chain$3$CMakeMaterial
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$_initializeAndCopyString DD imagerel _initializeAndCopyString
	DD	imagerel _initializeAndCopyString+77
	DD	imagerel $unwind$_initializeAndCopyString
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$CRenderClassGetMesh DD imagerel $LN20@CRenderCla
	DD	imagerel $LN20@CRenderCla+293
	DD	imagerel $unwind$CRenderClassGetMesh
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$CRenderClassGetStaticDataBuffer DD imagerel $LN26@CRenderCla
	DD	imagerel $LN26@CRenderCla+424
	DD	imagerel $unwind$CRenderClassGetStaticDataBuffer
;	COMDAT xdata
xdata	SEGMENT
$unwind$CRenderClassGetStaticDataBuffer DQ 00007640f00060f01r ; 1.02782e-308
	DQ	0700b320f0006340fr		; 5.2777e+231
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$CRenderClassGetMesh DQ 00006340a00040a01r ; 8.62672e-309
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$_initializeAndCopyString DQ 00007640f00060f01r ; 1.02782e-308
	DQ	0700b320f0006340fr		; 5.2777e+231
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$3$CMakeMaterial DQ 0000ae40000020021r	; 1.51453e-308
	DD	imagerel $LN23@CMakeMater
	DD	imagerel $LN23@CMakeMater+217
	DD	imagerel $unwind$CMakeMaterial
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$2$CMakeMaterial DQ 0000ae41400061421r	; 1.51457e-308
	DQ	0000834050009740fr		; 1.1408e-308
	DD	imagerel $LN23@CMakeMater
	DD	imagerel $LN23@CMakeMater+217
	DD	imagerel $unwind$CMakeMaterial
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$CMakeMaterial DQ 0000b540e00060e01r	; 1.5754e-308
	DQ	06006c008f00a320er		; 3.81287e+154
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$CDestroyMaterial DQ 00006340a00040a01r	; 8.62672e-309
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$3$CMakeRenderClass DQ 0000ae40000020021r	; 1.51453e-308
	DD	imagerel $LN29@CMakeRende
	DD	imagerel $LN29@CMakeRende+326
	DD	imagerel $unwind$CMakeRenderClass
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$2$CMakeRenderClass DQ 0000ae41400061421r	; 1.51457e-308
	DQ	0000834050009740fr		; 1.1408e-308
	DD	imagerel $LN29@CMakeRende
	DD	imagerel $LN29@CMakeRende+326
	DD	imagerel $unwind$CMakeRenderClass
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$CMakeRenderClass DQ 0000b540e00060e01r	; 1.5754e-308
	DQ	06006c008f00a320er		; 3.81287e+154
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$CDestroyRenderClass DQ 00006344500064501r ; 8.62797e-309
	DQ	07006320a0007640ar		; 4.30736e+231
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$CRenderClassGetName DQ 00008641400081401r ; 1.1669e-308
	DQ	00006341400075414r		; 8.62693e-309
	DD	070103214H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$CRenderClassSetMaterial DQ 00008641400081401r ; 1.1669e-308
	DQ	00006341400075414r		; 8.62693e-309
	DD	070103214H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$CRenderClassGetMaterial DQ 00007640f00060f01r ; 1.02782e-308
	DQ	0700b320f0006340fr		; 5.2777e+231
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$2$CRenderClassGetMaterialID DQ 00006340000020021r ; 8.62651e-309
	DD	imagerel $LN45@CRenderCla
	DD	imagerel $LN45@CRenderCla+335
	DD	imagerel $unwind$CRenderClassGetMaterialID
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$0$CRenderClassGetMaterialID DQ 00006340500020521r ; 8.62661e-309
	DD	imagerel $LN45@CRenderCla
	DD	imagerel $LN45@CRenderCla+335
	DD	imagerel $unwind$CRenderClassGetMaterialID
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$CRenderClassGetMaterialID DQ 00008741000061001r ; 1.17559e-308
	DQ	0e00c321000075410r		; -4.72551e+154
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$CRenderClassSetTriMaterialSingle DQ 00007640f00060f01r ; 1.02782e-308
	DQ	0700b320f0006340fr		; 5.2777e+231
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$CRenderClassGetTriMaterialSingle DQ 00007640f00060f01r ; 1.02782e-308
	DQ	0700b320f0006340fr		; 5.2777e+231
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$CRenderClassSetTriMaterials DQ 00007640f00060f01r ; 1.02782e-308
	DQ	0700b320f0006340fr		; 5.2777e+231
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$CRenderClassGetTriMaterial DQ 00007640f00060f01r ; 1.02782e-308
	DQ	0700b320f0006340fr		; 5.2777e+231
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$CRenderClassGetTriMaterialID DQ 00007640f00060f01r ; 1.02782e-308
	DQ	0700b320f0006340fr		; 5.2777e+231
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$CRenderClassSetVertexDataBuffer DQ 00008641400081401r ; 1.1669e-308
	DQ	00006341400075414r		; 8.62693e-309
	DD	070103214H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$CRenderClassGetVertexDataBuffer DQ 00007640f00060f01r ; 1.02782e-308
	DQ	0700b320f0006340fr		; 5.2777e+231
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$2$CRenderClassGetVertexDataBufferID DQ 00006340000020021r ; 8.62651e-309
	DD	imagerel $LN45@CRenderCla
	DD	imagerel $LN45@CRenderCla+329
	DD	imagerel $unwind$CRenderClassGetVertexDataBufferID
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$0$CRenderClassGetVertexDataBufferID DQ 00006340500020521r ; 8.62661e-309
	DD	imagerel $LN45@CRenderCla
	DD	imagerel $LN45@CRenderCla+329
	DD	imagerel $unwind$CRenderClassGetVertexDataBufferID
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$CRenderClassGetVertexDataBufferID DQ 00008741000061001r ; 1.17559e-308
	DQ	0e00c321000075410r		; -4.72551e+154
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$CRenderClassSetStaticDataBuffer DQ 00008641400081401r ; 1.1669e-308
	DQ	00006341400075414r		; 8.62693e-309
	DD	070103214H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$2$CRenderClassGetStaticDataBufferID DQ 00006340000020021r ; 8.62651e-309
	DD	imagerel $LN45@CRenderCla
	DD	imagerel $LN45@CRenderCla+329
	DD	imagerel $unwind$CRenderClassGetStaticDataBufferID
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$0$CRenderClassGetStaticDataBufferID DQ 00006340500020521r ; 8.62661e-309
	DD	imagerel $LN45@CRenderCla
	DD	imagerel $LN45@CRenderCla+329
	DD	imagerel $unwind$CRenderClassGetStaticDataBufferID
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$CRenderClassGetStaticDataBufferID DQ 00008741000061001r ; 1.17559e-308
	DQ	0e00c321000075410r		; -4.72551e+154
END
