; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30148.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_C@_0BB@PCMBDCPA@CMakeDrawContext@		; `string'
PUBLIC	??_C@_0DJ@EIKFGPFD@CMakeDrawContext?5failed?5because@ ; `string'
PUBLIC	??_C@_0BE@HOGEHINH@CDestroyDrawContext@		; `string'
PUBLIC	??_C@_0DL@LFGDIGNN@CDestroyDrawContext?5failed?5beca@ ; `string'
PUBLIC	??_C@_0BJ@EAOHDOEJ@CDrawContextSetDrawInput@	; `string'
PUBLIC	??_C@_0EA@DJLGMIMC@CDrawContextSetDrawInput?5failed@ ; `string'
PUBLIC	??_C@_0DM@MDGIDHBK@CDrawContextSetDrawInput?5failed@ ; `string'
PUBLIC	??_C@_0BJ@DEFJPCAF@CDrawContextGetDrawInput@	; `string'
PUBLIC	??_C@_0EA@GPIOOBCC@CDrawContextGetDrawInput?5failed@ ; `string'
PUBLIC	??_C@_0DM@FIFDEFCI@CDrawContextGetDrawInput?5failed@ ; `string'
PUBLIC	??_C@_0DK@LPJBMIHJ@CDrawContextGetDrawInput?5failed@ ; `string'
PUBLIC	??_C@_0CC@IAIDGGOF@CDrawContextGetDrawInputSizeByt@ ; `string'
PUBLIC	??_C@_0EJ@PEJJEMJL@CDrawContextGetDrawInputSizeByt@ ; `string'
PUBLIC	??_C@_0EF@LNECBJCB@CDrawContextGetDrawInputSizeByt@ ; `string'
PUBLIC	??_C@_0BO@CBAHBNCM@CDrawContextGetLastDrawTimeMS@ ; `string'
PUBLIC	??_C@_0EF@ENLNFODN@CDrawContextGetLastDrawTimeMS?5f@ ; `string'
PUBLIC	??_C@_0P@FKLLMFGP@CDrawInstanced@		; `string'
PUBLIC	??_C@_0DG@CIBDKAFG@CDrawInstanced?5failed?5because?5d@ ; `string'
PUBLIC	??_C@_0DB@INGALEIM@CDrawInstanced?5failed?5because?5r@ ; `string'
PUBLIC	??_C@_0DC@FAHJIAKO@CDrawInstanced?5failed?5because?5i@ ; `string'
PUBLIC	??_C@_0DB@OMLAGJKB@Bad?5material?5state?4?5No?5material@ ; `string'
EXTRN	__imp_GetTickCount64:PROC
;	COMDAT ??_C@_0DB@OMLAGJKB@Bad?5material?5state?4?5No?5material@
CONST	SEGMENT
??_C@_0DB@OMLAGJKB@Bad?5material?5state?4?5No?5material@ DB 'Bad material'
	DB	' state. No materials exist in class.', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0DC@FAHJIAKO@CDrawInstanced?5failed?5because?5i@
CONST	SEGMENT
??_C@_0DC@FAHJIAKO@CDrawInstanced?5failed?5because?5i@ DB 'CDrawInstanced'
	DB	' failed because instanceCount was 0', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0DB@INGALEIM@CDrawInstanced?5failed?5because?5r@
CONST	SEGMENT
??_C@_0DB@INGALEIM@CDrawInstanced?5failed?5because?5r@ DB 'CDrawInstanced'
	DB	' failed because rClass was invalid', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_0DG@CIBDKAFG@CDrawInstanced?5failed?5because?5d@
CONST	SEGMENT
??_C@_0DG@CIBDKAFG@CDrawInstanced?5failed?5because?5d@ DB 'CDrawInstanced'
	DB	' failed because drawContext was invalid', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0P@FKLLMFGP@CDrawInstanced@
CONST	SEGMENT
??_C@_0P@FKLLMFGP@CDrawInstanced@ DB 'CDrawInstanced', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0EF@ENLNFODN@CDrawContextGetLastDrawTimeMS?5f@
CONST	SEGMENT
??_C@_0EF@ENLNFODN@CDrawContextGetLastDrawTimeMS?5f@ DB 'CDrawContextGetL'
	DB	'astDrawTimeMS failed because drawContext was invalid', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BO@CBAHBNCM@CDrawContextGetLastDrawTimeMS@
CONST	SEGMENT
??_C@_0BO@CBAHBNCM@CDrawContextGetLastDrawTimeMS@ DB 'CDrawContextGetLast'
	DB	'DrawTimeMS', 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_0EF@LNECBJCB@CDrawContextGetDrawInputSizeByt@
CONST	SEGMENT
??_C@_0EF@LNECBJCB@CDrawContextGetDrawInputSizeByt@ DB 'CDrawContextGetDr'
	DB	'awInputSizeBytes failed because inputID was invalid', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0EJ@PEJJEMJL@CDrawContextGetDrawInputSizeByt@
CONST	SEGMENT
??_C@_0EJ@PEJJEMJL@CDrawContextGetDrawInputSizeByt@ DB 'CDrawContextGetDr'
	DB	'awInputSizeBytes failed because drawContext was invalid', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0CC@IAIDGGOF@CDrawContextGetDrawInputSizeByt@
CONST	SEGMENT
??_C@_0CC@IAIDGGOF@CDrawContextGetDrawInputSizeByt@ DB 'CDrawContextGetDr'
	DB	'awInputSizeBytes', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0DK@LPJBMIHJ@CDrawContextGetDrawInput?5failed@
CONST	SEGMENT
??_C@_0DK@LPJBMIHJ@CDrawContextGetDrawInput?5failed@ DB 'CDrawContextGetD'
	DB	'rawInput failed because outBytes was NULL', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0DM@FIFDEFCI@CDrawContextGetDrawInput?5failed@
CONST	SEGMENT
??_C@_0DM@FIFDEFCI@CDrawContextGetDrawInput?5failed@ DB 'CDrawContextGetD'
	DB	'rawInput failed because inputID was invalid', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0EA@GPIOOBCC@CDrawContextGetDrawInput?5failed@
CONST	SEGMENT
??_C@_0EA@GPIOOBCC@CDrawContextGetDrawInput?5failed@ DB 'CDrawContextGetD'
	DB	'rawInput failed because drawContext was invalid', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BJ@DEFJPCAF@CDrawContextGetDrawInput@
CONST	SEGMENT
??_C@_0BJ@DEFJPCAF@CDrawContextGetDrawInput@ DB 'CDrawContextGetDrawInput'
	DB	00H						; `string'
CONST	ENDS
;	COMDAT ??_C@_0DM@MDGIDHBK@CDrawContextSetDrawInput?5failed@
CONST	SEGMENT
??_C@_0DM@MDGIDHBK@CDrawContextSetDrawInput?5failed@ DB 'CDrawContextSetD'
	DB	'rawInput failed because inputID was invalid', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0EA@DJLGMIMC@CDrawContextSetDrawInput?5failed@
CONST	SEGMENT
??_C@_0EA@DJLGMIMC@CDrawContextSetDrawInput?5failed@ DB 'CDrawContextSetD'
	DB	'rawInput failed because drawContext was invalid', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BJ@EAOHDOEJ@CDrawContextSetDrawInput@
CONST	SEGMENT
??_C@_0BJ@EAOHDOEJ@CDrawContextSetDrawInput@ DB 'CDrawContextSetDrawInput'
	DB	00H						; `string'
CONST	ENDS
;	COMDAT ??_C@_0DL@LFGDIGNN@CDestroyDrawContext?5failed?5beca@
CONST	SEGMENT
??_C@_0DL@LFGDIGNN@CDestroyDrawContext?5failed?5beca@ DB 'CDestroyDrawCon'
	DB	'text failed because drawContext was invalid', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BE@HOGEHINH@CDestroyDrawContext@
CONST	SEGMENT
??_C@_0BE@HOGEHINH@CDestroyDrawContext@ DB 'CDestroyDrawContext', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0DJ@EIKFGPFD@CMakeDrawContext?5failed?5because@
CONST	SEGMENT
??_C@_0DJ@EIKFGPFD@CMakeDrawContext?5failed?5because@ DB 'CMakeDrawContex'
	DB	't failed because renderBuffer was invalid', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BB@PCMBDCPA@CMakeDrawContext@
CONST	SEGMENT
??_C@_0BB@PCMBDCPA@CMakeDrawContext@ DB 'CMakeDrawContext', 00H ; `string'
PUBLIC	CDrawInstanced
PUBLIC	CDraw
PUBLIC	CDrawContextGetLastDrawTimeMS
PUBLIC	CDrawContextGetDrawInputSizeBytes
PUBLIC	CDrawContextGetDrawInput
PUBLIC	CDrawContextSetDrawInput
PUBLIC	CDestroyDrawContext
PUBLIC	CMakeDrawContext
;	COMDAT pdata
pdata	SEGMENT
$pdata$CDrawInstanced DD imagerel $LN669@CDrawInsta
	DD	imagerel $LN669@CDrawInsta+435
	DD	imagerel $unwind$CDrawInstanced
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$1$CDrawInstanced DD imagerel $LN669@CDrawInsta+435
	DD	imagerel $LN669@CDrawInsta+468
	DD	imagerel $chain$1$CDrawInstanced
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$3$CDrawInstanced DD imagerel $LN669@CDrawInsta+468
	DD	imagerel $LN669@CDrawInsta+1197
	DD	imagerel $chain$3$CDrawInstanced
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$4$CDrawInstanced DD imagerel $LN669@CDrawInsta+1197
	DD	imagerel $LN669@CDrawInsta+1241
	DD	imagerel $chain$4$CDrawInstanced
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$5$CDrawInstanced DD imagerel $LN669@CDrawInsta+1241
	DD	imagerel $LN669@CDrawInsta+1318
	DD	imagerel $chain$5$CDrawInstanced
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$CDrawContextGetLastDrawTimeMS DD imagerel $LN20@CDrawConte
	DD	imagerel $LN20@CDrawConte+296
	DD	imagerel $unwind$CDrawContextGetLastDrawTimeMS
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$CDrawContextGetDrawInputSizeBytes DD imagerel $LN26@CDrawConte
	DD	imagerel $LN26@CDrawConte+426
	DD	imagerel $unwind$CDrawContextGetDrawInputSizeBytes
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$CDrawContextGetDrawInput DD imagerel $LN32@CDrawConte
	DD	imagerel $LN32@CDrawConte+526
	DD	imagerel $unwind$CDrawContextGetDrawInput
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$CDrawContextSetDrawInput DD imagerel $LN36@CDrawConte
	DD	imagerel $LN36@CDrawConte+479
	DD	imagerel $unwind$CDrawContextSetDrawInput
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$CDestroyDrawContext DD imagerel $LN28@CDestroyDr
	DD	imagerel $LN28@CDestroyDr+203
	DD	imagerel $unwind$CDestroyDrawContext
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$1$CDestroyDrawContext DD imagerel $LN28@CDestroyDr+203
	DD	imagerel $LN28@CDestroyDr+278
	DD	imagerel $chain$1$CDestroyDrawContext
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$2$CDestroyDrawContext DD imagerel $LN28@CDestroyDr+278
	DD	imagerel $LN28@CDestroyDr+356
	DD	imagerel $chain$2$CDestroyDrawContext
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$CMakeDrawContext DD imagerel $LN20@CMakeDrawC
	DD	imagerel $LN20@CMakeDrawC+319
	DD	imagerel $unwind$CMakeDrawContext
;	COMDAT xdata
xdata	SEGMENT
$unwind$CMakeDrawContext DQ 0000674d50006d501r	; 8.97869e-309
	DQ	06006320a0007340ar		; 3.71991e+154
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$2$CDestroyDrawContext DD 021H
	DD	imagerel $LN28@CDestroyDr
	DD	imagerel $LN28@CDestroyDr+203
	DD	imagerel $unwind$CDestroyDrawContext
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$1$CDestroyDrawContext DQ 00007740e00040e21r ; 1.03651e-308
	DD	063405H
	DD	imagerel $LN28@CDestroyDr
	DD	imagerel $LN28@CDestroyDr+203
	DD	imagerel $unwind$CDestroyDrawContext
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$CDestroyDrawContext DQ 00008540a00040a01r ; 1.15819e-308
	DD	06006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$CDrawContextSetDrawInput DQ 00009741a000a1a01r ; 1.31467e-308
	DQ	00007541a0008641ar		; 1.01916e-308
	DQ	0e016321a0006341ar		; -7.4399e+154
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$CDrawContextGetDrawInput DQ 00008641400081401r ; 1.1669e-308
	DQ	00006341400075414r		; 8.62693e-309
	DD	070103214H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$CDrawContextGetDrawInputSizeBytes DQ 00007640f00060f01r ; 1.02782e-308
	DQ	0700b320f0006340fr		; 5.2777e+231
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$CDrawContextGetLastDrawTimeMS DQ 00006340a00040a01r ; 8.62672e-309
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$5$CDrawInstanced DD 021H
	DD	imagerel $LN669@CDrawInsta
	DD	imagerel $LN669@CDrawInsta+435
	DD	imagerel $unwind$CDrawInstanced
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$4$CDrawInstanced DD 021H
	DD	imagerel $LN669@CDrawInsta+435
	DD	imagerel $LN669@CDrawInsta+468
	DD	imagerel $chain$1$CDrawInstanced
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$3$CDrawInstanced DQ 0000cf40a00040a21r	; 1.80137e-308
	DD	0dd405H
	DD	imagerel $LN669@CDrawInsta+435
	DD	imagerel $LN669@CDrawInsta+468
	DD	imagerel $chain$1$CDrawInstanced
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$1$CDrawInstanced DQ 0000ec40f00040f21r	; 2.05344e-308
	DD	0157408H
	DD	imagerel $LN669@CDrawInsta
	DD	imagerel $LN669@CDrawInsta+435
	DD	imagerel $unwind$CDrawInstanced
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$CDrawInstanced DQ 0e00fe21300051301r	; -5.34353e+154
	DQ	00000300b500c600dr		; 2.60991e-310
END
