; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30148.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	CInternalPipelineProjectTri
;	COMDAT pdata
pdata	SEGMENT
$pdata$CInternalPipelineProjectTri DD imagerel $LN13@CInternalP
	DD	imagerel $LN13@CInternalP+486
	DD	imagerel $unwind$CInternalPipelineProjectTri
;	COMDAT xdata
xdata	SEGMENT
$unwind$CInternalPipelineProjectTri DQ 00000882500072501r ; 7.39579e-310
	DQ	00002681200017818r		; 3.34668e-309
	DD	06204H
END
