; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30148.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_C@_0P@DMLIIFNC@CInternalAlloc@		; `string'
PUBLIC	??_C@_0O@JIACBMHP@CInternalFree@		; `string'
EXTRN	__imp_HeapAlloc:PROC
EXTRN	__imp_HeapFree:PROC
;	COMDAT ??_C@_0O@JIACBMHP@CInternalFree@
CONST	SEGMENT
??_C@_0O@JIACBMHP@CInternalFree@ DB 'CInternalFree', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0P@DMLIIFNC@CInternalAlloc@
CONST	SEGMENT
??_C@_0P@DMLIIFNC@CInternalAlloc@ DB 'CInternalAlloc', 00H ; `string'
PUBLIC	CInternalAlloc
PUBLIC	CInternalFree
;	COMDAT pdata
pdata	SEGMENT
$pdata$CInternalAlloc DD imagerel $LN14@CInternalA
	DD	imagerel $LN14@CInternalA+247
	DD	imagerel $unwind$CInternalAlloc
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$CInternalFree DD imagerel $LN14@CInternalF
	DD	imagerel $LN14@CInternalF+208
	DD	imagerel $unwind$CInternalFree
;	COMDAT xdata
xdata	SEGMENT
$unwind$CInternalFree DQ 00006340a00040a01r	; 8.62672e-309
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$CInternalAlloc DQ 00008641400081401r	; 1.1669e-308
	DQ	00006341400075414r		; 8.62693e-309
	DD	070103214H
END
