; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30148.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_C@_0BE@EKMGEMPI@Caesium?5Fatal?5Error@	; `string'
PUBLIC	??_C@_0BG@EGPLLKFF@CInternalSetLastError@	; `string'
PUBLIC	??_C@_0BL@GKPHBNOH@Current?5Caesium?5Error?3?5?$CFs?6@ ; `string'
PUBLIC	??_C@_0BF@KJCPEOKA@Caesium?5callstack?3?5?6@	; `string'
PUBLIC	??_C@_0BG@LOCNEPBC@CALLSTACK?5?$FL?$CF02d?$FN?3?5?$CFs?6@ ; `string'
PUBLIC	??_C@_0BG@DCEFHGBJ@CInternalGetLastError@	; `string'
EXTRN	__imp_strcpy_s:PROC
EXTRN	__imp___stdio_common_vfprintf:PROC
EXTRN	__imp_MessageBoxA:PROC
EXTRN	__imp___acrt_iob_func:PROC
COMM	?_OptionsStorage@?1??__local_stdio_scanf_options@@9@9:QWORD							; `__local_stdio_scanf_options'::`2'::_OptionsStorage
COMM	?_OptionsStorage@?1??__local_stdio_printf_options@@9@9:QWORD							; `__local_stdio_printf_options'::`2'::_OptionsStorage
_DATA	ENDS
;	COMDAT ??_C@_0BG@DCEFHGBJ@CInternalGetLastError@
CONST	SEGMENT
??_C@_0BG@DCEFHGBJ@CInternalGetLastError@ DB 'CInternalGetLastError', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BG@LOCNEPBC@CALLSTACK?5?$FL?$CF02d?$FN?3?5?$CFs?6@
CONST	SEGMENT
??_C@_0BG@LOCNEPBC@CALLSTACK?5?$FL?$CF02d?$FN?3?5?$CFs?6@ DB 'CALLSTACK ['
	DB	'%02d]: %s', 0aH, 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0BF@KJCPEOKA@Caesium?5callstack?3?5?6@
CONST	SEGMENT
??_C@_0BF@KJCPEOKA@Caesium?5callstack?3?5?6@ DB 'Caesium callstack: ', 0aH
	DB	00H						; `string'
CONST	ENDS
;	COMDAT ??_C@_0BL@GKPHBNOH@Current?5Caesium?5Error?3?5?$CFs?6@
CONST	SEGMENT
??_C@_0BL@GKPHBNOH@Current?5Caesium?5Error?3?5?$CFs?6@ DB 'Current Caesiu'
	DB	'm Error: %s', 0aH, 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0BG@EGPLLKFF@CInternalSetLastError@
CONST	SEGMENT
??_C@_0BG@EGPLLKFF@CInternalSetLastError@ DB 'CInternalSetLastError', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BE@EKMGEMPI@Caesium?5Fatal?5Error@
CONST	SEGMENT
??_C@_0BE@EKMGEMPI@Caesium?5Fatal?5Error@ DB 'Caesium Fatal Error', 00H ; `string'
PUBLIC	CInternalSetLastError
PUBLIC	fprintf
PUBLIC	_vfprintf_l
PUBLIC	__local_stdio_printf_options
PUBLIC	CInternalErrorPopup
PUBLIC	CInternalGetLastError
;	COMDAT pdata
pdata	SEGMENT
$pdata$CInternalSetLastError DD imagerel $LN25@CInternalS
	DD	imagerel $LN25@CInternalS+409
	DD	imagerel $unwind$CInternalSetLastError
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$fprintf DD imagerel $LN6@fprintf
	DD	imagerel $LN6@fprintf+69
	DD	imagerel $unwind$fprintf
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$_vfprintf_l DD imagerel $LN4@vfprintf_l
	DD	imagerel $LN4@vfprintf_l+68
	DD	imagerel $unwind$_vfprintf_l
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$CInternalGetLastError DD imagerel $LN15@CInternalG
	DD	imagerel $LN15@CInternalG+210
	DD	imagerel $unwind$CInternalGetLastError
;	COMDAT xdata
xdata	SEGMENT
$unwind$CInternalGetLastError DQ 00006340a00040a01r ; 8.62672e-309
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$_vfprintf_l DQ 00009640f00060f01r	; 1.30596e-308
	DQ	0700b520f0008340fr		; 5.30195e+231
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$fprintf DQ 07012521600041601r		; 7.11078e+231
	DD	030106011H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$CInternalSetLastError DQ 00009741a000a1a01r ; 1.31467e-308
	DQ	00007541a0008641ar		; 1.01916e-308
	DQ	0e016321a0006341ar		; -7.4399e+154
END
