; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.30148.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	CInternalPipelineProcessTri
;	COMDAT pdata
pdata	SEGMENT
$pdata$CInternalPipelineProcessTri DD imagerel $LN11@CInternalP
	DD	imagerel $LN11@CInternalP+161
	DD	imagerel $unwind$CInternalPipelineProcessTri
;	COMDAT xdata
xdata	SEGMENT
$unwind$CInternalPipelineProcessTri DQ 0000d640f00060f01r ; 1.86223e-308
	DQ	0700b920f000c340fr		; 5.35047e+231
END
